apiVersion: v1
kind: Service
metadata:
  name: auth-nodejs
  namespace: auth-nodejs
spec:
  type: ClusterIP
  selector:
    app: auth-nodejs
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
