context: minikube

name: auth-nodejs

dev:
  auth-nodejs:
    image: node:18
    imagePullPolicy: Never
    command: bash

    workdir: /code
    sync:
      - .:/code
      - $HOME/.ssh:/root/.ssh
    secrets:
      - $HOME/.npmrc:/root/.npmrc
