apiVersion: v1
kind: ConfigMap
metadata:
  name: streams-env-data
  namespace: streams
data:
  .env: |
    APP_ENV=development
    LOG_LEVEL=debug
    SYNC_MEMBERLIST_PORT=7946
    SYNC_CLUSTER_DNS_HOSTNAME=streams-headless.streams.svc.cluster.local
    SYNC_GRPC_PORT=9000
    SYNC_PEER_CLEANUP_INTERVAL=1
    SYNC_ETCD_URL=fraym-etcd.fraym-etcd.svc.cluster.local:2379
    SYNC_ETCD_USER=root
    SYNC_ETCD_PASSWORD=etcd1234
    SYNC_LOCK_PREFIX=streams
    CLIENTCHANNEL_PUBLISH_TIMEOUT=1
    CLIENTCHANNEL_SEND_TIMEOUT=1
    POSTGRES_CONNECTION=postgres://postgres:change-me@postgresql-hl.postgres.svc.cluster.local:5432
    S3_ENDPOINT=minio.minio.svc.cluster.local:9000
    S3_ACCESS_KEY=root
    S3_SECRET_KEY=change-me
    S3_SSL=false
    S3_BUCKET=streams
