apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-env-data
  namespace: auth
data:
  .env: |
    APP_ENV=development
    LOG_LEVEL=debug
    APP_SECRET=change-me
    CRUD_CLIENT_ADDRESS=crud.crud.svc.cluster.local:9000
    STREAMS_CLIENT_ADDRESS=streams.streams.svc.cluster.local:9000
    STREAMS_CLIENT_GROUP_ID=auth
