apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: grpc
      protocol: TCP
      port: 9000
      targetPort: 9000
