apiVersion: v1
kind: ConfigMap
metadata:
  name: crud-env-data
  namespace: crud
data:
  .env: |
    APP_ENV=development
    LOG_LEVEL=debug
    POSTGRES_CONNECTION=postgres://postgres:change-me@postgresql-hl.postgres.svc.cluster.local:5432
    STREAMS_CLIENT_ADDRESS=streams.streams.svc.cluster.local:9000
    STREAMS_CLIENT_KEEPALIVE_INTERVAL=40
    STREAMS_CLIENT_KEEPALIVE_TIMEOUT=3
    STREAMS_CLIENT_SEND_TIMEOUT=1
    STREAMS_CLIENT_GROUP_ID=crud
    PROJECTIONS_CLIENT_ADDRESS=projections.projections.svc.cluster.local:9000
    PROJECTIONS_CLIENT_KEEPALIVE_INTERVAL=40
    PROJECTIONS_CLIENT_KEEPALIVE_TIMEOUT=3
    PROJECTIONS_CLIENT_SEND_TIMEOUT=1
    S3_ENDPOINT=minio.minio.svc.cluster.local:9000
    S3_ACCESS_KEY=root
    S3_SECRET_KEY=change-me
    S3_SSL=false
    S3_BUCKET=crud
    IMGPROXY_URL=http://imgproxy-imgproxy.imgproxy.svc.cluster.local
